@rootUrl = http://localhost:8000
#API List

### Check server status

GET {{rootUrl}}

### post new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{ 
    "fName": "Hm",
    "lName": "Shrestha",
    "email":"homug@gmail.com",
    "phone": "0545sd343235",
    "password": "A12#roskfkf"

}
### activate user
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId":"SFVDFFDFFDFD",
    "t": "3aebe"
}

### login user
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"homug@gmail.com",
    "password": "A12#roskfkf"
}
### Get user profile

GET {{rootUrl}}/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbXVnQGdtYWlsLmNvbSIsImlhdCI6MTc1Njk4OTQxNCwiZXhwIjoxNzU2OTkwMzE0fQ.UqLobVW_xLpzkPL5I61vTKyDkTPp36HBWoNutKUMgpw

### Renew access JWT
GET {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbXVnQGdtYWlsLmNvbSIsImlhdCI6MTc2MjU3OTQ2NSwiZXhwIjoxNzY1MTcxNDY1fQ.ezEXo6DIsHanvzFJmsNVGNFwPb1Xua6FTJeMYK_VtRE

### OTP Request
GET {{rootUrl}}/api/v1/auth/otp
Content-Type: application/json

{
    "email": "homug@gmail.com"
}