@rootUrl = http://localhost:8000
#API List

### Check server status

GET {{rootUrl}}

### post new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{ 
    "fName": "Hm",
    "lName": "Shrestha",
    "email":"homug@gmail.com",
    "phone": "0545sd343235",
    "password": "A12#roskfkf"

}
### activate user
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId":"SFVDFFDFFDFD",
    "t": "3aebe"
}

### login user
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"homug@gmail.com",
    "password": "#Extreme76#"
}
### Get user profile

GET {{rootUrl}}/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbXVnQGdtYWlsLmNvbSIsImlhdCI6MTc1Njk4OTQxNCwiZXhwIjoxNzU2OTkwMzE0fQ.UqLobVW_xLpzkPL5I61vTKyDkTPp36HBWoNutKUMgpw

### Renew access JWT
GET {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbXVnQGdtYWlsLmNvbSIsImlhdCI6MTc2MjU3OTQ2NSwiZXhwIjoxNzY1MTcxNDY1fQ.ezEXo6DIsHanvzFJmsNVGNFwPb1Xua6FTJeMYK_VtRE

### OTP Request
POST {{rootUrl}}/api/v1/auth/otp
Content-Type: application/json

{
    "email": "homug@gmail.com"
}

### Reset-Password
POST {{rootUrl}}/api/v1/auth/reset-password
Content-Type: application/json

{
    "email": "homug@gmail.com",
    "password": "A12#dftew",
    "otp": 8379
}


### Books API

### GET public Books

GET {{rootUrl}}/api/v1/books

### GET Books by admin
GET {{rootUrl}}/api/v1/books/admin
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbXVnQGdtYWlsLmNvbSIsImlhdCI6MTc3NDc4NTg4NSwiZXhwIjoxNzc0Nzg2Nzg1fQ.I2avoDJT6mIAmIUk33fr1OupJaQT3tXKm8NCNx-tDQU

### Insert new book

POST {{rootUrl}}/api/v1/books
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbXVnQGdtYWlsLmNvbSIsImlhdCI6MTc3NDY5MTcyNywiZXhwIjoxNzc0NjkyNjI3fQ.dz4wFs-Wi-kY0hWh6WlBePChiQfp2sLjSWJ0LwpNL74

{
    "title": "Theory of time",
    "year": 2025,
    "author": "Stephen Hawking",
    "imgUrl": "https://example.com/images/clean-code.jpg",
    "isbn": "1548584859",
    "genre": "Science Fiction",
    "description": "Book about black holes and universe"
}

### UPDATE BOOKS

PUT {{rootUrl}}/api/v1/books
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbXVnQGdtYWlsLmNvbSIsImlhdCI6MTc3NTczOTcxNSwiZXhwIjoxNzc1NzQwNjE1fQ.ifkJJuNb9TNmwl6EfZX9u3QUj5Sa2XZAWunpkKQcHQE

{
    "title": "Theory of time",
    "year": 2025,
    "author": "Stephen Hawking",
    "imgUrl": "https://example.com/images/clean-code.jpg",
    "isbn": "1548584859",
    "genre": "Science Fiction",
    "status": "Active",
    "expectedAvailable": "2022-01-01",
    "description": "Book about black holes and universe",
    "_id": "69cdff0d8794dd57c2c3995c"
}