@rootUrl = http://localhost:8000
#API List

### Check server status

GET {{rootUrl}}

### post new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{ 
    "fName": "HOM",
    "lName": "GURUNG",
    "email":"hom@gmail.com",
    "phone": "0452099516",
    "password": "lkshsd"

}

